import { z } from 'zod';

export const voterSchema = z.object({
  nome: z.string().min(1, 'Nome é obrigatório'),
  cpf: z.string().optional(),
  ignoreCpf: z.boolean().optional(),
  nascimento: z.string().optional(),
  genero: z.string().min(1, 'Gênero é obrigatório'),
  nome_mae: z.string().optional(),
  whatsapp: z.string().min(1, 'WhatsApp é obrigatório'),
  telefone: z.string().optional(),
  titulo: z.string().optional(),
  zona: z.string().optional(),
  secao: z.string().optional(),
  cep: z.string().min(1, 'CEP é obrigatório'),
  logradouro: z.string().min(1, 'Logradouro é obrigatório'),
  cidade: z.string().min(1, 'Cidade é obrigatória'),
  bairro: z.string().min(1, 'Bairro é obrigatório'),
  numero: z.string().min(1, 'Número é obrigatório'),
  complemento: z.string().optional(),
  uf: z.string().optional(),
  categoria_uid: z.string().min(1, 'Categoria é obrigatória'),
  usuario_uid: z.string().min(1, 'Usuário é obrigatório'),
  empresa_uid: z.string().min(1, 'Empresa é obrigatória'),
  indicacao: z.string().optional(),
  upload_id: z.string().optional(),
  upload_url: z.string().optional(),
  responsavel: z.string().optional(),
  registrarAtendimento: z.boolean().optional(),
  descricaoAtendimento: z.string().optional(),
  categoriaAtendimento: z.string().nullable().optional(),
  statusAtendimento: z.string().optional(),
});