-- Drop existing table if it exists (to avoid conflicts)
DROP TABLE IF EXISTS gbp_indicado CASCADE;

-- Create table for indicados with correct name
CREATE TABLE gbp_indicado (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    nome text null,
    cidade text null,
    bairro text null,
    gbp_empresas bigint null,
    constraint gbp_indicado_pkey primary key (id),
    constraint gbp_indicado_gbp_empresas_fkey foreign key (gbp_empresas) references gbp_empresas (id) on delete cascade
);

-- Create indexes for better performance
CREATE INDEX idx_indicado_empresa ON gbp_indicado(gbp_empresas);
CREATE INDEX idx_indicado_nome ON gbp_indicado(nome);

-- Add trigger to automatically update timestamps
CREATE OR REPLACE FUNCTION update_indicado_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_indicado_timestamp
    BEFORE UPDATE ON gbp_indicado
    FOR EACH ROW
    EXECUTE FUNCTION update_indicado_updated_at();