-- Drop existing table if it exists
DROP TABLE IF EXISTS gbp_indicado CASCADE;

-- Create table for indicados with correct structure
CREATE TABLE gbp_indicado (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    nome text not null,
    cidade text null,
    bairro text null,
    gbp_empresas bigint not null,
    constraint gbp_indicado_pkey primary key (id),
    constraint gbp_indicado_gbp_empresas_fkey foreign key (gbp_empresas) references gbp_empresas (id) on delete cascade
);

-- Create indexes for better performance
CREATE INDEX idx_indicado_empresa ON gbp_indicado(gbp_empresas);
CREATE INDEX idx_indicado_nome ON gbp_indicado(nome);
CREATE INDEX idx_indicado_cidade ON gbp_indicado(cidade);
CREATE INDEX idx_indicado_bairro ON gbp_indicado(bairro);

-- Add reference in eleitores table
ALTER TABLE gbp_eleitores 
ADD COLUMN IF NOT EXISTS indicado_id bigint REFERENCES gbp_indicado(id) ON DELETE SET NULL;